### ISSUE TITLE
feature request: specify number of API hits

### ISSUE THREAD

**Issue by proxenus** [theotherp/nzbhydra#104]
I hope I'm posting this in the right place. Thanks for all your work on this!

I have some free accounts that have very limited api hits like 10 or 30 per day, it would be nice to have hydra stop after the specified number.

**Comment by theotherp** [comment]
You've come to the right place! :-D

Yeah, I already gave that a shot and stopped. It isn't as easy as it sounds. For example it differs wildly when indexers reset the API hit counter. -4 hours UTC? +5 hours UTC? Should I reset the counter at 00:00 UTC and ignore that there might be hits left or already all gone at that point? Even if I wanted to provide an input for the time (which I don't because I don't want to pollute the config more than it already is), how do you find out when the counter of an indexer is reset?

Also, the question is why you want to stop. Do you want some hits left in case you want to manually search? So would you only want API hits on NZBHydra to count? Do you just want to prevent using more hits that you have (which you can't, hydra will stop when it gets a message that the hits are all used up).

If you have 10 hits for an indexer that's 100 minutes of sonarr hitting that indexer and all your hits are gone for the day. Add CP and less, depending on their sync delay.

You see, there are so many questions to be answered. I'll keep it open but don't expect the feature for some time.

**Comment by proxenus** [comment]
I thought about some of those too. Obviously these are just my opinions:
- No point doing any requests if it's not going to answer. Based on the backoff for failures will it back off more than 1 day if it stops responding for 18 hours? I think that some of these may slow down hydra's results too if they stop responding when you hit your limit and you have to wait for the timeout.
- I think it would be cool to be intelligent about the reset time, but it does make it excessively complicated. My opinion would be to just set it for 00:00UTC and in the end it would still balance out.

I think the point of why bother stopping is valid. In my case the response time to get results isn't a concern. I guess the solution if you want to save those limited hits for searches you only enable it for searches in hydra.

Thanks for all your work on this, I love the program!

**Comment by theotherp** [comment]
I'll keep it open and if I find the time I'll see what I can come up with.

**Comment by theotherp** [comment]
@proxenus If you want to help get this done contact some indexers and ask them when their API hits are reset (time of day and timezone). Perhaps they always use the same time. If possible open the API search result of every indexer and take a look at the pubdate values. It's possible that the UTC offset is the same as the time when the API hits are reset.

**Comment by steveulven** [comment]
Hi,  I have yet to try out NZBHydra and this was one major question I had. You made some good points above about the difficulty of this and I was going to recommend gathering this info and also maybe, if implemented, to have a note/recommendation under the setting to reduce API hit count a little for some wiggle room. Are you still interested in gathering counter reset times and hits/day for indexers and if so where would you like the info submitted? I'd like to help if I can.

**Comment by theotherp** [comment]
Sure. As I said, find out when indexers reset their counter and check it against their timezone (the UTC offset used in the pubdate). Post them here. Ideally there is some logic to the reset times.

In any case don't expect this feature too soon. I will want to rewrite some of my core logic before I add anything and I think this is a somewhat obscure feature.

**Comment by steveulven** [comment]
I did get somewhat a start, but going through it I'm starting to agree that it isn't a priority due to the great variance. I've collected (and still will continue) some API hits & NZBs/day for free and premium user tiers on a few sites. I don't have reset times yet, but did find that Oznzb has a rolling counter (that's the one that made me realize this'd require quite a bit of effort for a small payoff). I'll probably provide a Google Sheets or something that others can request write access to and add/edit entries for when/if you'd want to add this feature. And perhaps just giving the user the option to put in their own numbers would be easiest if someone really wanted the feature.

Also, I have tried out the program and love it. I no longer think I really require this feature, but do understand the value for those that would want it.

**Comment by Hellowlol** [comment]
Generally indexers lets your know if you have used up all api calls. We could just check for that message and disable that provider for xxx time.

**Comment by theotherp** [comment]
That's what already happens. This feature request aims to be able to stop before the limit is reached.

**Comment by Hellowlol** [comment]
Thanks! I'll read the issue better next time :p

**Comment by steveulven** [comment]
Thanks, this is nice! I did start a Gist table if this is helpful for future developments or for anyone that needs to know the API limits. It is incomplete, to say the least, and some info may have been assumptions rather than reality.

https://gist.github.com/steveulven/8df11c1e5a01d82aea74

**Comment by theotherp** [comment]
Great idea. I think you can look it up on each indexer in the profile settings. Usually VIP access gives you more limits and grabs than anybody could need.

**Comment by steveulven** [comment]
This was actually harder than I figured, which is why I didn't get very far. Not many indexers display all this info in an easy to find place, but yeah, the profile settings is one of the best places to start, but usually only gives you the info for your membership status (if you're a free user, you can get better info from your profile and then from looking at upgrade perks).

I'll try to add more later. Perhaps even a column with the API URL would be helpful.

**Comment by proxenus** [comment]
I can try to look some of this information up. I can't find anywhere to edit the gist table. Should I just put the info I find in here?

**Comment by steveulven** [comment]
You could make a fork of it, which might be better for others as a one-stop-shop.

**Comment by albino1** [comment]
Maybe instead of using Gist just create a new NZBHydra Wiki page that everyone can edit.
