### ISSUE TITLE
Sonarr cannot retrieve nzb file if Hydra is behind apache .htpasswd

### ISSUE THREAD

**Issue by kylerw** [theotherp/nzbhydra#111]
If I have reverse proxy enabled and require a login from .htpasswd sonarr fails to get the nzb from Hydra and hits a 401.

Disabling apache password for Hydra and enabling Hydra's built in auth does fix it....

**Comment by theotherp** [comment]
So you provide a link like https://user:password@www.whatever.com/nzbhydra to sonarr and it works with hydra's auth enabled and htpasswd disabled?

Are they on the same machine? Just use the local address without reverse proxy.

Never considered this, will have a look.

**Comment by theotherp** [comment]
Oh right, that wouldn't work. When sonarr tries to retrieve the NZB it gets asked for a user and password which it obviously doesn't know. If you use auth in hydra then auth is still disabled for all API requests because there you authenticate with the API key.

Just don't use apache's auth. Use the local address if possible.

You might try setting a base url like https://user:password@www.whatever.com/nzbhydra but not sure if that would work.

**Comment by theotherp** [comment]
I just realized that hydra will use the external URL for NZBs when a base URL is set so sonarr will try to access that one via apache and not be able to auth. So currently there is no way to get it to run with htaccess, I think.

**Comment by kylerw** [comment]
Yeah, that's what I noticed. Possible to add a setting for external or internal HOST when sending NZB URLs? They're on the same box so that would be ideal. That way they can still be exposed and secured in the same manner.

**Comment by theotherp** [comment]
Ugh I dunno. Will see.

**Comment by theotherp** [comment]
Please try the latest commit to develop. There're now two different settings for the URL base and the external URL.

If you remove the external URL value after migration you should be able to access NZB Hydra through the reverse proxy but the links in the API results should still link to the local URL, allowing sonarr to access them.

If you want friends to use your instance of NZB Hydra they're probably SOL because the links from the results will be the internal ones.

**Comment by theotherp** [comment]
Yeah, this is getting complicated but I always wanted to make this tool as configurable as possible.
