### ISSUE TITLE
FR: Log failed logins + lockout after x number of failed attempts

### ISSUE THREAD

**Issue by albino1** [theotherp/nzbhydra#113]
I attempted a few failed logins to see what would happen and didn't see any output in the console or in the log.

A lot of people are running NZBHydra open on the Internet so I thought it might be prudent to log any failed logins + details so that we could at least be aware of what's going on.  There might be other security related logging that should be done too, though I can't think of anything off the top of my head.

Also, if it doesn't already exist, it might be wise to include a lockout after a certain amount of failed logins to prevent people from trying to brute force entry.

**Comment by theotherp** [comment]
Good idea. One might think that I should've though of that but some things you need to be reminded of.

**Comment by theotherp** [comment]
Alright, this was somewhat more complicated than I thought it would be. It logs nearly every failed authentication with IP. The first time you have to wait 2 seconds for the next try, then 4, then 6 and so on. I say "nearly" because if you reload the page while waiting it could be considered a failed login. But I only consider a login "new" if it uses another username and password than the last one.

The failed logins are saved per IP so it should be possible to login for you while another user waits (which you want when somebody else wants to maliciously access your server).
