### ISSUE TITLE
better sonarr support

### ISSUE THREAD

**Issue by M0UL** [theotherp/nzbhydra#128]
when adding nzbhydra as indexer to sonarr, it wil only grab the first 100rss feeds items. after talking with one of the sonarr devs (chat log below). it seems that hydra doesnt support paging in there rss feed.

> M0UL: seems sonarr is only grabbing the first 100 entry from a indexer. means things nzbhydra are seles for sonarr.
Taloth: that's what paging is for.
M0UL: i dont think paging works for hydra
M0UL: i havent seen it grab more then 100 enteries per rss sync
Taloth: Are the results properly sorted by pubdate?
M0UL: nope
Taloth: In the xml response it should be sorted properly.
Taloth: If it isn't, then that's the problem, coz sonarr uses the pubdate to determine if additional pages are needed

**Comment by theotherp** [comment]
Paging works and sonarr easily pulls hundreds of results (a couple of pages) from my instance.

**Comment by theotherp** [comment]
Looks fine to me. Results are sorted by pubdate descending and paging works fine too. Also I have no idea what "means things nzbhydra are seles for sonarr" is supposed to mean.

I just started my test installation of sonarr and it requested 11 pages from hydra with a total of 1100 results. Your problem might be related to the indexers you use. Some return an invalid "total" amount, DogNZB for example always returns 100. Hydra will then stop after the first request because how could it know that there actually are / might be more than 100 results. Do an API search on the indexers you use and take a look. The line should say something like

    <newznab:response offset="0" total="100" />

(this is from DogNZB).
