### ISSUE TITLE
Show title in stats & history for ID based searches

### ISSUE THREAD

**Issue by theg1nger** [theotherp/nzbhydra#142]
When searching for a TV show, under the History & Stats. When I look at the search History. The query title is missing if I select a ID when searching. (Thanks for fixing the TV seasons %d format error btw!) 

![screen shot 2016-02-21 at 2 06 42 pm](https://cloud.githubusercontent.com/assets/12101893/13205071/5f45d530-d8a4-11e5-99a0-385791f08faf.png)

**Comment by theotherp** [comment]
Technically that's correct because you didn't search using a query but instead using IDs. It would be possible but somewhat complicated to include the title. Because then if you would click on the search icon to repeat a search it would be done not only with the IDs but also with the title, so it would be another query. This would also result in newznab indexers potentially returning less results, for example when results don't contain the title. Say you search for a show "The show" using the ID, one of the results could be named "Show", but searching for "The show" would not return this (very contrived, but you get the gist).

**Comment by theotherp** [comment]
Well, I could add the title of the show / movie dynamically. So not as the query but somewhere as extra info so that you know what's behind the shown ID. Will think about it.

**Comment by WinstonP** [comment]
Makes sense. I guess if the show is not tagged on the indexer with an ID but still has a title of the file indexed then one way would show a result and the other would not. Correct?

**Comment by theotherp** [comment]
For any newznab indexer that's worth its money it's very unlikely that a simple search for a show's title would return a result that's not already matched to that show.
