### ISSUE TITLE
Support newznab book query arguments

### ISSUE THREAD

**Issue by philborman** [theotherp/nzbhydra#168]
Hi, I'm working on LazyLibrarian (https://github.com/DobyTang/LazyLibrarian.git) and trying to send searches to nzbhydra but it doesn't seem to work with the same parameters we use for nZEDb servers, or newznab+ servers. Is there any documentation on the parameters you use?

At the moment our parameters are causing nzbhydra to generate an internal server error

2016-03-05 18:17:41 DEBUG   [NewzNabPlus] - nzb Search parameters set to {'author': u'Stephen Edger', 'apikey': u'xxxx', 't': 'book', 'cat': '7020', 'title': u'Snatched'}
2016-03-05 18:17:41 DEBUG   No data returned from https://www.example.com for Stephen Edger Snatched
2016-03-05 18:17:41 ERROR   Error 403 opening url HTTP Error 500: INTERNAL SERVER ERROR

**Comment by theotherp** [comment]
Perhaps you could send me an example of the URL you're calling. Hydra should be able to compatible to newznab API, it works with Sonarr, SickBeard, NZB360 and Mylar.

I just did a test this afternoon and was able to search and download from my hydra instance just fine.

**Comment by theotherp** [comment]
Ok, got it. I don't support any book specific searches. Should've thought of that. Will implement them tomorrow if everything goes well.

**Comment by theotherp** [comment]
Note to self: Return and log better message if unexpected query arguments are used.

**Comment by philborman** [comment]
Excellent, thanks for the fast response.
One of our users requested we add nzbhydra support - looks interesting, 
might add a server on my RaspberryPi, just waiting for the new model to 
arrive in the post.

Phil.

**Comment by theotherp** [comment]
@philborman I don't know the internal logic of LL, but why does it use "t=book" when the caps don't say that book-search is included? I'm currently implementing the book search and so far haven't found an indexer that actually supports that type of search.

In hydra I check the caps of each indexer to see if it actually supports the search type.

**Comment by philborman** [comment]
We don't check the capabilities, just try a few searches in sequence until one works.
I might have a look at including capability searches, but it's not my project. Original author is not around any more.  Book search t=book works with usenet-crawler, oznzb, nzbplanet and others. Documented here...
https://nzbplanet.net/apihelp

**Comment by theotherp** [comment]
Yeah, I took the API from http://newznab.readthedocs.org/en/latest/misc/api/#book-search

Unfortunately I don't have access to any of those indexers.

**Comment by philborman** [comment]
Hi again,

Just a few thoughts I wondered if you could ponder...

Seems using capabilities is problematic.
The providers I use are nzbgeek, usenet-crawler, oznzb, nzbplanet, and 
also torrentbytes, eutorrents thepiratebay via a jackett torznab server.

All support t=book with author=xxx and title=xxx as parameters, but none 
mention this in their caps.
Some providers caps show searching as available but without giving any 
supported parameters.
This is  oznzb...

<caps>
<serverappversion="0.2.3p"version="0.1"title="oznzb"strapline="The Best 
NZB Indexer - search and download NZB 
files."email="webadmin@oznzb.com"url="https://api.oznzb.com/"image="https://api.oznzb.com/theme/oznzb/images/banner.jpg"/>
<limitsmax="100"default="100"/>
<registrationavailable="yes"open="yes"/>
<searching>
<searchavailable="yes"/>
<tv-searchavailable="yes"/>
<movie-searchavailable="yes"/>
<audio-searchavailable="yes"/>
</searching>
<categories>
<categoryid="1000"name="Console">
......

so I am currently just using caps to get the category IDs I need, and 
trying book search with
t=book
author=authorname
title=bookname
cat=7000,7010 or whatever the caps returned for book and ebook 
category/subcat.

All the newznab+ servers that I have tried accept these parameters, but 
nzedb servers don't.
They return "unknown function" for t=book, which I can trap and store so 
we don't try that server with t=book again.

Also seems we can probably tell if we're nzedb or newznab by looking at 
the book category.
All newznab seem to use id=7000  and all nzedb seem to use id=8000.

This seems a better way forward to me unless/until the providers update 
their caps to match their real capabilities and documentation. Any thoughts?

Phil

**Comment by theotherp** [comment]
I never knew how to find out if an indexer is nzedb or newznab (programmatically). Would be good to have a reliable indicator, but as I don't even know for sure myself I was never able to find a correlation between caps (e.g.) and the indexer type.

But if what you say is true I apparently use mostly nzedb indexers because of the ones that I have API access to (nzbs.org, dognzb, nzb.su, usenet-crawler, 6box, Drunken Slug and one or two others I don't remember) only one supported book queries. And only about 1/3 reports supported params in the caps and one doesn't even do that. None, even the one that supports the book queries, says so in the caps.

So, yeah, you're right regarding the book search. But I only supported movie and tv search from the beginning and those are always properly reported in the caps. I try to find the supportedParams attributes in the cats and if those don't exist I do a "brute force" check like you describe. Unfortunately with TV and movie search the providers behave inconsistently: some return an empty list and some just ignore it and return all latest entries from the category (for example doing a tvdb based TV search just returns all latest TV releases). So I search for a popular TV show and check if the search returns any results that are at least 95% correct.

So until I supported book searches the caps check mostly worked and for the few cases it did not I did the brute force search.

I think your approach is better, we shouldn't rely on the indexer's caps as they're nearly always incomplete in some way. In a perfect world the caps pages would be updated or even generated dynamically considering the underlying indexer and its capabilities, but that probably won't happen. I might change my code to always go that way, rather interpret the facts than rely on documentation.

Thanks for the input!

**Comment by philborman** [comment]
Category for books seems to be a reliable indicator, not subcat as they 
differ between implementations, eg magazines can be 7010, 7020, 7040
Books always seem to be 7000 on newznab, always 8000 on nzedb

Seems the only indexer we have in common is usenet-crawler, which uses 
7000 and supports t=book
I will stick with my current method. Not perfect but it's the best I can 
think of for now.
Kind regards,

Phil.
