### ISSUE TITLE
Add download limit to indexers

### ISSUE THREAD

**Issue by wizzy99** [theotherp/nzbhydra#247]
In addition to API limit, I have a few indexers that limit the number of downloads per day.  Would be great if hydra would stop trying to grab files even if the API limit hasn't been reached.

**Comment by jant90** [comment]
I second this request, this would be really useful with backup indexers that I don't have a subscription on (free/trial accounts). These indexers sometimes have files that can't be found on my main (paid) or have been DMCA'd. While most of the time these API limits are never hit, there are situations where these API limits are hit quickly, for example when an entire season is missing from my main indexer and all episodes are downloaded separately from the backup indexer.

**Comment by steveulven** [comment]
I do have a Gist cheat-sheet [here](https://gist.github.com/steveulven/8df11c1e5a01d82aea74#file-nzb-indexer-api-info-md) with API & download limits for many indexers. @albino1 suggested this go in the Wiki after I posted in Issue #104 so I may do this later after I've updated a few more.

**Comment by atyoung** [comment]
Arguably, there is no reason to return results at all from an indexer that has no downloads left.

**Comment by theotherp** [comment]
It's still on my todo list.

**Comment by famewolf** [comment]
Probably a pipe dream but when the hard limit has been reached sure would be nice if an option was available to have it try the pull later similar to how it temporarily disables an indexer...if a particular indexer is the only one giving me a particular nzb and I've indicated I want it...why not defer 24 hours then try again and push it to sabnzbd.....I usually schedule large downloads for the early hours of the morning due to download speeds being so much better and that would pair nicely.   Not sure it's feasible though.

**Comment by theotherp** [comment]
@famewolf Nah, I'm afraid that won't happen, too much work, too complicated.

**Comment by theotherp** [comment]
Alright, this has been open for too long. I just implemented it. See the disclaimer in the changelog.
