### ISSUE TITLE
OZnzb Details Link

### ISSUE THREAD

**Issue by albino1** [theotherp/nzbhydra#252]
Most indexers that have a dedicated API URL auto-redirect the Details link from `api.indexer.com` to `www.indexer.com` or just `indexer.com`.  Examples might be NZB.su or DOGnzb, where if you click the Details link for:

`https://api.nzb.su/details/123c84594e49917a6cd15b7983311f0bf2`

It auto-redirects to:

`https://www.nzb.su/details/123c84594e49917a6cd15b7983311f0bf2`

Giving you a correct Details page.

However, OZnzb (and possibly others?) fail to auto-redirect to the Details page, and instead just redirect you to root.  So:

`https://api.oznzb.com/details/123c84594e49917a6cd15b7983311f0bf2`

Redirects to:

`https://www.oznzb.com/`

Which is obviously worthless.

I'm not sure what the message or bug here is other than "OZnzb should handle their damn redirect better", but maybe there's something to be said for not linking to `api.` in the first place, and instead having NZBH default to `www`.  Or just drop the subdomain period and go to `indexer.com/details/`.

I can definitely see this as a situation where it just is what it is, and there's nothing really to be done about it.  It's just something I noticed and thought was odd, so feel free to close it if there's no obvious solution.

**Comment by theotherp** [comment]
That's not necessarily their fault. Because the details links provided in the indexer API results often lead to different pages (nfo, comments, what not) I build the links myself, using the configured host, in this case "http://api.oznzb.com". A quick and dirty fix would be to replace "api" with "www".

**Comment by judhat2** [comment]
It's probably better if I check if oznzb's admin can fix it. I'll try their forum first.

**Comment by judhat2** [comment]
I figured out the problem.  The original link to the oznzb comments is https://legend**api**.oznzb.com/details/xxxxx.  This link redirects correctly to the details page.  Hydra replaces the "api" with "www" and hence, produces the comment link as legend**www**.oznzb.com, which doesn't redirect.

The original problem for this issue has been corrected by oznzb.  All the links redirect correctly now.  I found several other indexers that use api.indexer.com as their api url. Althub.co.za doesn't redirect correctly, but they don't provide that url as the comments link in their api. NZBgeek doesn't redirect, [but you have coded appropriately for that.](https://github.com/theotherp/nzbhydra/blob/master/nzbhydra/searchmodules/newznab.py#L455) Dognzb, nzb.su, and nzbplanet use that format, but they all redirect correctly.  I don't know of any other that use api.indexer.com.

Perhaps you can remove this code all together, since oznzb has fixed it. Although, that could be a problem for api.althub.co.za if Hydra builds its own comments link based on the api address. Or add an exception for https://legendapi.oznzb.com?

**Comment by albino1** [comment]
If it's redirecting blahblah**api**blahblah to blahblah**www**blahblah then that's probably just a basic bug and an easy regex fix I would think.

**Comment by theotherp** [comment]
I now save the details link for every search result in the database, so there's probably no reason to modify the link anyway.

**Comment by theotherp** [comment]
The problem is that indexers provide the details link in different formats and tags in their results. Some use the GUID, some the comments attribute, some the info attribute, but all support http://<theirbaseurl>/details/<guid>

No I try to get the link from the GUID first, then from the comments, thet as a fall back I use the old approach replacing "api" with "www". I don't have an account for oznzb so I can't test if that helps.

**Comment by judhat2** [comment]
Thanks! It's working well now.
