### ISSUE TITLE
Add support for API functions details and getnfo

### ISSUE THREAD

**Issue by theotherp** [theotherp/nzbhydra#29]
See http://newznab.readthedocs.org/en/latest/misc/api/#details and http://newznab.readthedocs.org/en/latest/misc/api/#getnfo

**Comment by soakes** [comment]
Are you aware NZBHydra won't work with Couchpotato until "details" API is implemented? You responded to this reddit post saying it should work: https://www.reddit.com/r/usenet/comments/3vna42/presenting_nzb_hydra_the_usenet_meta_search_alpha/cyq19cf — However, couchpotato repeatedly blacklists hydra. A great concept, I have put this issue on my watch list :)

**Comment by theotherp** [comment]
My Hydra instance has been running on CP for months without issues. Perhaps it's a configuration issue? CP should not need to ask for details as all details are already provided in the search results.

**Comment by soakes** [comment]
CP will run fine for the first approx five results and then it will block for 15 miniutes.  The only way to get round the block is to fully restart CP. 

If you only have one or two things which are being downloaded every now and then, you wont notice this issue/flaw.  However if you have 5 or more things which are being downloaded at once or found at the same time, this is when this problem is very visable.

**Comment by theotherp** [comment]
Alright, I don't use CP very much so that explains it.

The implementation isn't easy for a number of reasons and I have some other stuff on my list. I might get around to doing it on the weekend. Sorry for the complications.

**Comment by soakes** [comment]
No worries.  Thanks for taking a look into it.  

I am doing some further testing and debugging myself and if I find anything useful, I will let you know.

**Comment by albino1** [comment]
Wouldn't it make more sense to ask the CP developer to just stop it from blocking NZBHydra in the first place?

**Comment by Mirabis** [comment]
According to https://github.com/CouchPotato/CouchPotatoServer/blob/c4fad95cd24bffd814572e8fd08c4f2f5d14f59b/couchpotato/core/media/_base/providers/nzb/newznab.py it doesn't do too much with the detail url. Can't we just hardcode a response with no password as temporary workaround?

But personally, i have not seen CP any issue on my instance(s).

**Comment by soakes** [comment]
Its only being blocked because of the error which is being returned.  This is a safety feature of his software so it doesnt hammer bad servers or ones with issues/load etc.  He has no way to tell that its Hydra anyway as its only using an newznab compatible API at the end of the day.  

Disabling the check would disable it on every site not just Hydra which would be bad.  I am sure I could probbaly find the code/check anyway and hash the check, if worst case, just that every update would break it again tho which is why I was trying to see about getting it fixed at the root of the problem i.e. hydra rather then a quick hack which will work until he updates again.

Right now I am using a quick simple work around and that is just to have have CP go direct instead of using Hydra.  Sadly defeats the purpose of using Hydra but at least I still have an all in one search engine for those rare times when I manually look for other things outside of the scope of CP+Sonarr.

I would love for Hydra to be fixed so that it doesn't generate these errors i.e. enable this support so that everyone is happy (software wise).  

I understand you don't have time to correct/fix right now and sadly I don't know python as well as I would like to but I think you miss understand how serious/annoying this issue is for a lot of us and I am surpised that more people haven't said anything yet.  Either that or they grab very little at any one time hence doesnt notice this issue.  As I said before, Hydra does work, but only for first few (5 approx) results then borks.

**Comment by theotherp** [comment]
I'm making some progress here. But not all indexers even support getting dedicated information about a particular search result. It will probably not work with NZBClub and Womble. All details requests for results from these indexers will return an empty RSS. But I guess that's still a lot better than no details at all.

**Comment by soakes** [comment]
Thank you.  Sorry for the delay, its been one of them weeks.

I have just applied the latest version and it apears "touch wood" to of fixed all the issues with CP.  Its no longer blocking in CP.

Thank you so much for your hard work.

I will keep an eye on it over the next few days but seems like its now all been resolved.

Thank you once again.
