### ISSUE TITLE
CouchPotato is unable to download NZB using API

### ISSUE THREAD

**Issue by schumi2004** [theotherp/nzbhydra#361]
What do you expect to happen? What does happen? 
CP should download and send NZB to downloader like it does with other nweznab sites but in fact it returns an error for nzbhydra where it doesn't for other newznab sites:

09-07 14:16:55 ERROR
[ase.providers.nzb.newznab] Failed download from 192.168.1.2: Traceback (most recent call last): File "/volume1/@appstore/couchpotatoserver/share/CouchPotatoServer/couchpotato/core/media/_base/providers/nzb/newznab.py", line 198, in download data = self.urlopen(url, show_error = False, headers = {'User-Agent': Env.getIdentifier()}) File "/volume1/@appstore/couchpotatoserver/share/CouchPotatoServer/couchpotato/core/plugins/base.py", line 227, in urlopen response.raise_for_status() File "/usr/local/couchpotatoserver/share/CouchPotatoServer/libs/requests/models.py", line 837, in raise_for_status raise HTTPError(http_error_msg, response=self) HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://192.168.1.2:5075/getnzb?apikey=xxx&searchresultid=55673

* Have you searched for this problem? 
Yes but didn't found a solution. Since Sonarr is working perfect using the API i'm thinking this could also be a CP issues instead of NZBHydra? Manually accessing the api using browser (using the url used by CP) also returns nothing.

* Can the problem be reproduced? How?
Yes, configure NZBHydra as indexer, and manually pick a presented releases in a wanted movie.

I didn't wanted to upload the logs returned by nzbhydra as i thought it still contained too much sensitive info (provider api keys) therefore i have copied the last (and important part) of the log.
http://pastebin.com/GttQZaEn

**Comment by theotherp** [comment]
This might be caused by the database redesign some time ago. It's possible that CP has stored a link to a result that was retrieved before the database was cleaned up and duplicate results deleted. Do a new search in CP and check if this problem still occurs.

By the way, the system tab has a bugreport section that provides you with an anonymized version of the log and config (although it's a bit buggy and sometimes doesn't work). If you think that log contains too much sensitive info let me know and send me an example (with the actually sensitive information replaced, obviously).
