### ISSUE TITLE
Request: shows stats of indexer sites

### ISSUE THREAD

**Issue by phit42** [theotherp/nzbhydra#382]
Not entirely certain if the API's provide this information, but it would be very useful if the stats of an nzb were shown with it.
With stats I mean the additional information like # of comments and # of votes on usenet-crawler, or # of grabs, # of fails, # of comments on NZBCat.

**Comment by theotherp** [comment]
Only a couple of indexers provide these stats in their API results. But when they do I could show them, yes. Not sure if I want to add new columns to the result table for that, it's already pretty busy in there. Perhaps a tooltip or something like that.

**Comment by judhat2** [comment]
I think it would be good to see if any nzbs have comments attached to them.  I think most indexers return this info.

**Comment by albino1** [comment]
The percentage of NZBs with comments is extremely low, but with that said, if there are comments usually they're important.  More of the "unpack failed, corrupt rar" variety and less of the "Spider-man is sooooo cool" kind :)

**Comment by theotherp** [comment]
In before NZBMatrix was so awesome... But that was before download automation. I never would've dreamed of tools like we have them now.

There're a couple of stats that I could show in the tooltip if they're provided: # grabs, # comments, # files, completion. I haven't checked how many indexers actually provide these but what the hell, if they do I already got them in their API response and could show just show them.

**Comment by albino1** [comment]
If it's easy then I'm all for it.  Can't see a downside :)

**Comment by judhat2** [comment]
Thanks for adding the stats. However, I think it looks a little busy with number of files, grabs, and comments all crunched together.  The number of files could probably be taken out. I don't think that gives any valuable info when looking for a release to download.  Just my two cents.

I have two thoughts about the comments.  A link leading directly to the comments of a release is given in the api. This could be put into a clickable link for the user to easily see the comment.  

In addition, it's also possible with newznab indexers to retrieve the comments similar to retrieving the contents of an .nfo file.  [It's documented here.](https://newznab.readthedocs.io/en/latest/misc/api/#comments) It's not a currently available function for nZEDb indexers.
Looks like this: `https://www.indexer.com/api?t=comments&id=<guid>&apikey=<apikey>`

Note that it's not `guid=xxxx` as the docs say, it is `id=xxxx`. I guess the docs were never updated or incorrectly labeled.

**Comment by theotherp** [comment]
To be honest, I only added the files stat because it was there and I could... I could just remove it, I don't care about the stats one way or the other.

Linking to the comments link would be possible, sure. You can also just click the details link until then.

If I ever add code that recognizes nzedb from newznab indexers I might add getting the responses using the API, but until then probably not. As @albino1 said there aren't so many comments anyway.

**Comment by albino1** [comment]
I agree with @judhat2 that at the very least I would ditch the number of files and leave only grabs/comments.  Since comments are so rare, and probably reasonably important if they exist, maybe bold them when they're greater than 0 so that it stands out, or only display the number if they exist at all.

If it was me (and it's not!) I think maybe I'd probably make the comments kind of like the NFO column where it only displays if there are comments to be found.

**Comment by theotherp** [comment]
Yeah that's probably a better idea.

**Comment by phit42** [comment]
Thx for the super-fast response and enhancement, @theotherp . I like it. And I agree with @albino1 to leave # of files out might make it easier to read. Also, I would support moving comments to a column like NFO however if it really shows only in case of comments. NFO currently shows "maybe" and has "no nfo found" for most of them. I personally like the idea of keeping the number and then having a tooltip on the number showing the comments. Anyway, thank you!
