### ISSUE TITLE
Store book and audio related search data and redesign history

### ISSUE THREAD

**Issue by theotherp** [theotherp/nzbhydra#396]
Audio or book search API requests use query data that should be stored in the database and shown in the search history (author, title, etc.).

The search history should probably be revised so it doesn't contain columns for each of these values which will be empty most of the time anyway. Perhaps one column for the query and one for all the meta data:

Date | Query | Category | Meta data | Access | Username
------------ | -------------| -------------| -------------| -------------| -------------
2016-10-16 09:28 | Some query | ALL | | Internal | Admin
2016-10-16 09:28 |  | Movies HD | IMDB ID: 1234567 | API | 
2016-10-16 09:28 |  | TV HD | TVDB ID: 12345, Season: 1, Episode: 1 | API | 
2016-10-16 09:28 |  | Ebooks | Author: William Shakespeare, Book: Hamlet | API |

**Comment by albino1** [comment]
Sometimes I've wanted to clear out a bunch of junk history, but not the entire history, so maybe there could be a way to delete individual entries.  I'm probably the only one who is OCD enough to want to do that, and it's probably not worth any real effort to make happen, but since you're redesigning the history anyway I thought I'd bring it up if it's easy :)

**Comment by theotherp** [comment]
Hm yeah, that's not going to work. I need the searches in the database because other entries rely on it. I could probably add a new table that stores which entries to hide but that's indeed a lot of work for an obscure feature ;-)

**Comment by albino1** [comment]
Hah, no problem.  Thanks!
