### ISSUE TITLE
Please support Cardigann

### ISSUE THREAD

**Issue by manderss99** [theotherp/nzbhydra#404]
Cardigann is a new more stable alternative to jackett.

https://github.com/cardigann/cardigann

**Comment by theotherp** [comment]
Have you checked that it doesn't work?

**Comment by manderss99** [comment]
I've added it, seemingly ok, but when I search I don't get any results...

**Comment by theotherp** [comment]
Will take a look

**Comment by theotherp** [comment]
Wow, no WCD, PTP or BTN? I could only test with IPT and provided other indexers don't return differently formatted results then I got it fixed.

**Comment by albino1** [comment]
> Wow, no WCD, PTP or BTN? I could only test with IPT and provided other indexers don't return differently formatted results then I got it fixed.

That's the first thing that I noticed when I looked at it.

Thought, it's not like PTP really works with Jackett either :)

**Comment by famewolf** [comment]
Does Cardigann support ANY public torrent sites such as kat.ch, extratorrent.cc and TPB?  I looked at Jackett and even got it working on freenas but since it only used closed trackers wasn't of interest to me.  I'm not on hi speed so spending alot on private trackers or trying to maintain high upload rates just isn't feasible.  First I've heard of Cardigann.
