### ISSUE TITLE
AltHub - TV only Search Type

### ISSUE THREAD

**Issue by Spritzup** [theotherp/nzbhydra#433]
Good Evening,

I just setup AltHub as another indexer and notice that it's showing "TV" as the available search type.  My feeling is that it should also support "Movies", and that is what is reflected on the nzbhydra wiki.  In any case, I was asked to post here to see if somebody could verify this.

Thanks!

Spritz

**Comment by judhat2** [comment]
AltHub does support searching movies via the IMDB id. E.G. https://althub.co.za/api?t=movie&imdbid=0088763

The problem is that their t=caps doesn't show the information.  https://althub.co.za/api?t=caps
It's a problem on their end that they need to fix.  Actually, several indexers support using the IMDB id, but don't show it in their t=caps info. NZBhydra doesn't pick it up because it relies upon that information when choosing what categories the indexer supports.

Until AltHub fixes it, just manually add the support for movies and IMDB in AltHub's configuration in NZBhydra.

**Comment by theotherp** [comment]
Great, I was hoping somebody would jump in here (and kinda expecting it would be you ;-))

I could theoretically always do the "brute force" check which I currently only fall back on if the indexer doesn't provide the caps, but I agree that the indexer should rather fix their information.

**Comment by Spritzup** [comment]
That's great, thanks for the response!

Does a list exist anywhere (or do you happen to know) what indexers don't have the t=caps info correct?

Thanks again, I really appreciate it!

~Spritz

**Comment by judhat2** [comment]
> I could theoretically always do the "brute force" check

That might be a good idea.  I just wrote a quick bash script to check the t=caps of 32 indexers and if they include this info. 11 of them returned `<movie-search available="no" supportedParams="q"/>`, however they do actually support an IMDB id search with valid results.  The indexers are pfmonkey, nzeeb, casstormnzb, newztown, nzbindex.in, keagaming, anonzbs, nzbnoob, miatrix, nzbs.in, and dusky.deepcave.
