### ISSUE TITLE
NZBs.org forbidden

### ISSUE THREAD

**Issue by bradmurray** [theotherp/nzbhydra#491]
I am trying to use nzbs.org. It worked on the initial setup of the system yesterday, but now the service seeps to be returning a 403. I have tried via curl and the API seems to be working fine with my key. Here is the log.

```
2016-12-27 10:36:12,445 - ERROR - search_module - Thread-33 - NZBs.org: Error while connecting to URL https://nzbs.org/api?extended=1&t=search&offset=0&apikey=<APIKEY>&limit=100&password=<PASSWORD>&q=1080p&maxage=30: 403 Client Error: Forbidden for url: https://nzbs.org/api?extended=1&t=search&offset=0&apikey=<APIKEY>&limit=100&password=<PASSWORD>&q=1080p&maxage=30
2016-12-27 10:36:12,468 - INFO - search_module - Thread-33 - NZBs.org: Disabling indexer temporarily due to access problems. Will be reenabled in 14 minutes
2016-12-27 10:36:12,625 - INFO - search - Thread-32 - NZBs.org returned 0 results
```

**Comment by theotherp** [comment]
Works fine with my API key. What happens when you open that URL in your browser? Use

https://nzbs.org/api?extended=1&t=search&offset=0&apikey=APIKEY&limit=100&password=1&q=1080p&maxage=30

**Comment by bradmurray** [comment]
Like I said in the initial report. That works fine for me via curl. It also works in the browser.

**Comment by theotherp** [comment]
Post your debug info (as already requested in the issue template).

Are you using a proxy by any chance that might cause the request to be routed differently?

**Comment by bradmurray** [comment]
When I put it in debug mode I don't get any more information, just the 403. In fact there is not a single DEBUG entry in the log even though it has been in debug mode since yesterday. I am not using a proxy on the outgoing connection, just on the web server for nzbhydra for incoming connections (to run behind https).

**Comment by theotherp** [comment]
Have you restarted hydra? Also the debug Infos contain a sanitized version
of your settings.

Am 28.12.2016 15:40 schrieb "Brad Murray" <notifications@github.com>:

When I put it in debug mode I don't get any more information, just the 403.
In fact there is not a single DEBUG entry in the log even though it has
been in debug mode since yesterday. I am not using a proxy on the outgoing
connection, just on the web server for nzbhydra for incoming connections
(to run behind https).

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/theotherp/nzbhydra/issues/491#issuecomment-269485572>,
or mute the thread

**Comment by theotherp** [comment]
Right... Debugging mode is not meant for you. Set the logfile level to "Debug", restart, try again and then post the debug infos which I *repeatedly* asked you to do.

**Comment by theotherp** [comment]
Does it work now?

**Comment by bradmurray** [comment]
Yes. It seems to.
