### ISSUE TITLE
Populating the Supported Search Types

### ISSUE THREAD

**Issue by Mirabis** [theotherp/nzbhydra#51]
I've added a wiki page where users can add the supported search params for their providers [here](https://github.com/theotherp/nzbhydra/wiki/Supported-Search-Types)

It might make it easier to make presets, and/or provide docs for those setting up their indexers.

**Comment by theotherp** [comment]
Great idea, thanks.

**Comment by albino1** [comment]
The title of the Wiki changed and now @Mirabis' original link doesn't work.  Here's the current link:

https://github.com/theotherp/nzbhydra/wiki/Supported-Search-Types-And-Indexer-Hosts

I would be more than happy to contribute to this, but is there an easy way to figure out what each indexer supports?

If possible, rather than hardcoding a bunch of indexer attributes, would it be easier to incorporate a button on the indexer configuration that queries the indexer to see what it supports?  For example, if you queried and asked for `81189` and it returned `Breaking Bad` then you would know it supported TVDB and could add that to the database configuration accordingly.

A lot of indexers are in the process of migrating from TVRage to TVDB/TVMaze, and the ones that aren't probably will be soon, so it would make sense to automate this somehow instead of pushing updates every time an indexer changes.

**Comment by theotherp** [comment]
Yeah, I've thought about something like that. Unfortunately indexers seem to behave differently when an unknown ID is used; some return no results, some return all the category's results.

I will give it a try tomorrow. Unfortunately I have no functionality to do something like this on a regular basis, so perhaps we'll do it the first time an indexer is added and it can be triggered manually via the backend. Do requests using all the known IDs and check if the indexer either returns no results or some with the wrong titles. Of course this would fail if an indexer would, for example, support the ID but not have any results indexed for the particular title

**Comment by albino1** [comment]
Yeah, that could be a problem.  For TV you'd need to use a currently airing show with a unique name that would almost certainly be indexed.  Something like `2 Broke Girls` maybe.

**Comment by Mirabis** [comment]
I thought of the same, but this information is listed on {indexer}/apihelp , and is not present in /t=caps :(. And even so, the admin may have forgotten to update his api docs >.<

**Comment by theotherp** [comment]
I use Avengers for movies and Game of Thrones for TV. Both should be indexed at least once for a couple of years.

**Comment by Mirabis** [comment]
Some of the indexers put the supported params in their caps":

```
<searching>
<search available="yes" supportedParams="q,group"/>
<tv-search available="yes" supportedParams="q,rid,tvdbid,vid,traktid,tvmazeid,imdbid,tmdbid,season,ep"/>
<movie-search available="yes" supportedParams="q,imdbid"/>
<audio-search available="no" supportedParams=""/>
</searching>
```

**Comment by theotherp** [comment]
Cool.

**Comment by albino1** [comment]
With the `Check search types` option now is there any need to fill in the Wiki and create Presets?  I'm not against the idea, just asking.  If you still want to create Presets based on the Wiki info then let me know and I'll start filling some of it in.

**Comment by theotherp** [comment]
For the search types, no, but it's still helpful to know the hosts. 
Thanks.

**Comment by theotherp** [comment]
The automated check seems to be stable for now. Would be nice if it would be executed automatically whenever the user adds a new indexer.
