### ISSUE TITLE
Hydra can no longer be added to Sonarr

### ISSUE THREAD

**Issue by Pixelmort91** [theotherp/nzbhydra#544]
I can't add hydra to sonarr on my new install
hydra don't responde to the query
"No results were returned from your indexer"

sonarr send an empty query to hydra when you want to add it but since [#533](https://github.com/theotherp/nzbhydra/issues/533)
hydra no longer works when the query is empty

**Comment by theotherp** [comment]
Post your debugging info.

**Comment by Pixelmort91** [comment]
2017-02-11 15:37:44,724 - INFO - web - Thread-48 - API search request: SearchRequest [ type "tv", forbiddenWords "[]", requiredWords "[]", offset "0", loadAll "False", limit "100" ]
2017-02-11 15:37:44,726 - INFO - search - Thread-48 - Starting new search: SearchRequest [ type "tv", forbiddenWords "[]", requiredWords "[]", offset "0", loadAll "False", limit "100" ]
2017-02-11 15:37:46,675 - INFO - search - Thread-48 - Some indexers were not selected for this search: 
Query needed: Binsearch, NZBClub, NZBIndex
2017-02-11 15:37:46,696 - INFO - search - Thread-48 - All indexers exhausted
2017-02-11 15:37:46,697 - INFO - search - Thread-48 - Returning 0 results
2017-02-11 15:37:46,699 - INFO - web - Thread-48 - API search request completed in 1975 ms

**Comment by theotherp** [comment]
For fuck's sake, read this: https://github.com/theotherp/nzbhydra/blob/master/ISSUE_TEMPLATE.md

**Comment by theotherp** [comment]
You need to add "proper" indexers which support update queries.

**Comment by kriskater** [comment]
This is a lame problem in Sonarr/Radarr.

It seems like both applications test the correctness of the connection to a custom newznab server by expecting a search result when setting up the connection. However, it seems as though both application fail to provide a search query.

You can trick both apps by providing an addition parameter when setting up the custom newznab connection:

&q=test

Once added. Open de settings for the custom newznab server again and remove te value "&q=test" again so that it will not interfere with your queries. Strangely, but luckily, upon editing the correctness of the connection is not tested.

**Comment by theotherp** [comment]
Interesting solution.

But using Hydra on Sonarr without any "proper" indexer you're gonna have a bad time.

**Comment by kriskater** [comment]
Of course you should still add your own indexers. It's just that you cannot complete the setup in Sonarr/Radarr without nzbhydra returning any results. 

I did not check with any additional indexers configured, but with the defaults ones (with api queries enabled), it just doesn't work. I expect lots of people are running into this.

**Comment by theotherp** [comment]
Without adding any further indexers sonarr and radarr won't find anything
when updating even after you complete the setup. You'll need to trigger a
search for it to find something.

I might improve logging but in my experience users who don't add any
newznab indexers are those that don't check the log anyway.

**Comment by kriskater** [comment]
Did you ever try adding a fresh nzbhydra install as an indexer in Sonarr or Radarr?

**Comment by theotherp** [comment]
You mean an installation without any indexers enabled? No, why would I?

**Comment by crypticedge** [comment]
Because out of the box, nzbhydra pulls from several free indexers. 

The problem is how sonarr/radarr "test" to validate if it's a good source. What it searches for is bunk, so nzbhydra returns no results. If it tested by getting a listing of API exposed categories instead, it could at least validate it's real without falsely calling a working setup bad. or retesting and randomly killing the entire source because of a query that isn't actually a good query to begin with.

**Comment by YipYup** [comment]
@crypticedge Is this an issue because of container usage? Or what type of user scenario would this become an inconvenience? I'm not taking sides, just trying to understand.
