### ISSUE TITLE
'Indexer statuses' exposes api keys on connection errors

### ISSUE THREAD

**Issue by euphoria0** [theotherp/nzbhydra#58]
Even with a restricted settings page any connection error exposes your api keys at the 'Indexer statuses' page.

For example:
>Connection failed: HTTPSConnectionPool(host='example-indexer.com', port=443): Max retries exceeded with url: /api?apikey=*myexposedapikey*&[...]

For reproducing this issue just point example-indexer.com to 127.0.0.1 in your hosts file.

**Comment by scriptzteam** [comment]
Can confirm this ...

**Comment by Cozza38** [comment]
In addition to this, are we able to have configuration for the "history and stats" to be hidden or admin authenticated if its something that's easy to do.

**Comment by scriptzteam** [comment]
simple .htaccess file can do it quickly, simply whitelist only your ip other will be blacklisted, or do .htaccess auth

**Comment by Cozza38** [comment]
I tried blocking the path of the config page before we had separate authentication and found that the block didn't work at the web server due to the page being ajax(?).

I would assume "History and Stats" will be the same.

A dirty solution was to remove the tab in the html and block the URL at the web server.

**Comment by theotherp** [comment]
Will look into it. The stats thing will be done with another issue.

**Comment by theotherp** [comment]
See #59

**Comment by theotherp** [comment]
Should be solved. Please let me know if you find sensitive data anywhere else.
