### ISSUE TITLE
Womble Not Displayed as Selected

### ISSUE THREAD

**Issue by albino1** [theotherp/nzbhydra#63]
Even though Womble is set to Preselect in the default installation it doesn't show up as selected on the index page.  I tried disabling the Preselect and re-enabling it, but it still doesn't show up.  I'm attaching a screenshot where it's not visible.

![al-nzbhydra-womble](https://cloud.githubusercontent.com/assets/12164957/11911981/0048d292-a5de-11e5-9f2f-6cb2c6939fe9.jpg)

**Comment by theotherp** [comment]
Yeah, that's because Womble doesn't support "proper" searching with RSS. I would need to use the web interface and then parse the results which I haven't included yet, so womble is only used for "queryless" searches like sonarr does to just get the latest TV releases. I will create a new enhancement issue for Womble search support.

**Comment by albino1** [comment]
Ah, okay.  I don't personally care about Womble support, I just thought it was a bug.

**Comment by theotherp** [comment]
I'll add a note to the config. I internally differentiate between different types of indexer which isn't always clear to the user. Thanks for the report, anyway.
