### ISSUE TITLE
Add Audiobook Category

### ISSUE THREAD

**Issue by imadunatic** [theotherp/nzbhydra#98]
Just set this up the past weekend, looks very promising coming from NZBmegasearch.  Curious if I could throw in a feature request for audiobook category?

Thanks for the work on this.

**Comment by theotherp** [comment]
Generally this isn't a problem. But I'll have to see how close the different newznab indexers keep to the "official" categories. Many only barely use the same category IDs, meaning that a search for category 3030 (which is officially for audiobook) may return audiobooks from some indexers and porn from others. As it's hard to specify certain suffixes for audiobooks on raw indexers their results would also be mostly crap (for example looking for an ebook I add "ebook or pdf or mobi or epub" to an ebook search).

I'll see if I can come up with an implementation that provides reasonable results. This will take some time because for now I want to get everything stable and tested before I add any new features.

**Comment by imadunatic** [comment]
No problem, in my limited testing I was just manually adding audio to the end of my searches; as you said, works great sometimes, not so great other times (I don't use raw indexers so I can't comment)

Again, thanks for the work on this. I had lost all hope that we would get another nzb aggregator anytime soon...

**Comment by theotherp** [comment]
Alright. I decided not to add anything to the query (no "audio" or something like that); using a minimum size of 50MB reduces most of the ebooks from the results and using the author in the search query should result in mostly correct results, even for raw indexers.

That being said most newznab indexers don't seem to care a lot for audiobooks. Take a look on the websites of your indexers to see how many they've actually indexed...

Please report back if you have any ideas on how to improve the results. 

You might want to search without the audiobook category to check if there are results in the wrong categories.

**Comment by imadunatic** [comment]
Thanks @theotherp , I didn't even thinking about using the minimum size filter.... That's good enough for me!  Been using this more and more, almost ready to release it to the wild for my buddies to try out. Only thing I'm having trouble with, which I assume is a config issue, is locking up the admin side with a separate password. It appears to me, that once I'm in, I'm in for everything. But I haven't completely tested this through and through. 

Thanks for all the work.

**Comment by albino1** [comment]
If people start allowing their friends to use it then the indexers are going to start banning it.  Just something to keep in mind.

**Comment by imadunatic** [comment]
Huh... does this not pull through my server first? I have NZBMega setup currently servicing a remote server of mine and I know at least some of my indexers (dog for example) will place restrictions if they detect multiple IP hits, which I've never had happen. 

I was assuming that Hydra also pulled to my server first even if I was accessing remotely... @theotherp is this not the case? 

As far as for my buddies, it amounts to maybe 10 manual searches a month, so I'm not too worried about that, but I have my server up north pulling off the API of NZBMega, so that might be a problem for me if this isn't the case.

**Comment by theotherp** [comment]
Admin access works, tested it right now. You might want to test it in private mode because you'll be still logged in for the same session.

All accesses go through the server, the indexers will not know who uses NZBHydra. Compared to API hits every couple of minutes by automation tools a few manual searches shouldn't make a difference.

**Comment by imadunatic** [comment]
My remote server only searches every 60 minutes anyways, I don't believe in hammering indexers personally.... Thanks for confirmation.
